=head1 XuLA FPGA Designs

<b><i>The contents of this directory are deprecated!</i></b> 
The latest stuff is in the https://github.com/xesscorp/XuLA directory.
But if you really do want these older files, then read on...

Common and board-specific design files for the XuLA boards.

=over 4

=item * XuLA_lib

A directory containing HDL files describing modules that are useful in a variety of larger designs.

=item * 50

A directory containing design projects for the XuLA-50 board
(done using Xilinx ISE WebPACK 13).

=item * 200

A directory containing design projects for the XuLA-200 board
(done using Xilinx ISE WebPACK 13).

=back
